### ISSUE TITLE
Tap Postgres - Error with log based replication method

### ISSUE THREAD

**Issue by beratwallee** [transferwise/pipelinewise#1151]
Hi Community!

I'm trying to use the "log-based" replication method. In the source database (Postgresql), we have configured it to be able to read the database binary logs by following your documentation. But I'm getting the following issue when I try to run the pipeline:

```
time=2024-01-19 11:18:24 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:42 log_level=DEBUG message=Detected PostgreSQL version: 150004
time=2024-01-19 11:18:25 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:601 log_level=INFO message=Set session wal_sender_timeout = 10800000 milliseconds
time=2024-01-19 11:18:25 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:605 log_level=INFO message=Request wal streaming from 8/2EECA520 to 8/2EECC418 (slot pipelinewise_db)
time=2024-01-19 11:18:35 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:695 log_level=INFO message=Waiting for first wal message
time=2024-01-19 11:18:45 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:695 log_level=INFO message=Waiting for first wal message
time=2024-01-19 11:18:55 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:695 log_level=INFO message=Waiting for first wal message
time=2024-01-19 11:19:05 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:695 log_level=INFO message=Waiting for first wal message
time=2024-01-19 11:19:14 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py:650 log_level=INFO message=Breaking - latest wal message 8/2EEECAF0 is past end_lsn 8/2EECC418
time=2024-01-19 11:19:14 logger_name=tap_postgres file=/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py:450 log_level=CRITICAL message=[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/bin/tap-postgres", line 8, in <module>
    sys.exit(main())
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py", line 451, in main
    raise exc
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py", line 448, in main
    main_impl()
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py", line 437, in main_impl
    do_sync(conn_config, args.catalog.to_dict() if args.catalog else args.properties,
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py", line 322, in do_sync
    state = sync_logical_streams(conn_config, list(streams), state, end_lsn, state_file)
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/__init__.py", line 221, in sync_logical_streams
    state = logical_replication.sync_tables(conn_config, logical_streams, state, end_lsn, state_file)
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/tap_postgres/sync_strategies/logical_replication.py", line 733, in sync_tables
    singer.write_message(singer.StateMessage(value=copy.deepcopy(state)))
  File "/.../java/pipelinewise/pipelinewise/.virtualenvs/tap-postgres/lib/python3.8/site-packages/singer/messages.py", line 303, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:01:02.548550
-------------------------------------------------------
```

I can see in the target database (Postgresql) that the table is replicated, and all the data are there. But I get this error on the first run, and from the second run, I still get the same error, and the data are not aligned anymore.

Could anybody help me, please?
Many thanks!

**Comment by beratwallee** [comment]
The problem was that I was connecting to the target database without any password. It is a test database that I configured using a user with permission to access the DB without any password. By adding the passwords, everything started working correctly.
