### ISSUE TITLE
Support for VIEW (instead of TABLE) as a tap source table for INCREMENTAL Replication Method

### ISSUE THREAD

**Issue by johnoscott** [transferwise/pipelinewise#224]
I have a source database table that does not have a primary key so can not be used for INCREMENTAL Replication Method.

However, I can create a VIEW in my database and JOIN to another table that does have a Primary key, making the VIEW suitable for INCREMENTAL Replication Method.

However when I try to use the view I get this error 

```
INFO Selected streams: ['MYSCHEMA-TBLINSTITUTION', 'MYSCHEMA-VIEWINSTITUTION'] 
INFO Use of log_miner requires fetching current scn...
INFO dsn: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=X.X.X.X)(PORT=1521))(CONNECT_DATA=(SID=XXXX)))
INFO Getting catalog objects from information_schema cache table...
INFO End SCN: 924906321 
INFO No currently_syncing found
INFO Beginning sync of stream(MYSCHEMA-VIEWINSTITUTION) with sync method(incremental)
INFO Stream MYSCHEMA-VIEWINSTITUTION is using incremental replication with replication key CHANGEDDATE
INFO dsn: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=X.X.X.X)(PORT=1521))(CONNECT_DATA=(SID=XXXXX)))
INFO select SELECT  "ABBREVIATION" , "ADDRESS1" , "ADDRESS2" , "ADDRESS3" , "ADDRSTATE" ,to_char( "CHANGEDDATE" ), "CHANGEDUID" , "COUNTRYCODE" , "COURSESURL" ,to_char( "CREATEDDATE" ), "CREATEDUID"..." 
                                FROM MYSCHEMA.VIEWINSTITUTION
                               ORDER BY CHANGEDDATE ASC
                               
Traceback (most recent call last):
  File "/app/.virtualenvs/target-snowflake/bin/target-snowflake", line 11, in <module>
    load_entry_point('pipelinewise-target-snowflake==1.0.8', 'console_scripts', 'target-snowflake')()
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 277, in main
    state = persist_lines(config, input, information_schema_cache)
  File "/app/.virtualenvs/target-snowflake/lib/python3.7/site-packages/target_snowflake/__init__.py", line 185, in persist_lines
    if config.get('primary_key_required', True) and len(o['key_properties']) == 0:
TypeError: object of type 'NoneType' has no len()
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 19, "tags": {}}
CRITICAL [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-oracle/bin/tap-oracle", line 11, in <module>
    load_entry_point('pipelinewise-tap-oracle==1.0.0', 'console_scripts', 'tap-oracle')()
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 565, in main
    raise exc
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 562, in main
    main_impl()
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 556, in main_impl
    do_sync(conn_config, args.catalog, args.config.get('default_replication_method'), state)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 533, in do_sync
    state = sync_traditional_stream(conn_config, stream, state, sync_method_lookup[stream.tap_stream_id], end_scn)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 488, in sync_traditional_stream
    state = do_sync_incremental(conn_config, stream, state, desired_columns)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/__init__.py", line 374, in do_sync_incremental
    state = incremental.sync_table(conn_config, stream, state, desired_columns)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/tap_oracle/sync_strategies/incremental.py", line 91, in sync_table
    singer.write_message(record_message)
  File "/app/.virtualenvs/tap-oracle/lib/python3.7/site-packages/singer/messages.py", line 218, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by cruzzan** [comment]
I agree, it would be really great if there was a way to specify the desired primary key of a view in a tab, so that views can be used to run incremental syncs as well.

Is there any way to do this at the moment? (Have i just not found it yet) Or is it perhaps a feature that could be added?

**Comment by koszti** [comment]
No, this feature is not available at the moment. It's possible to make it but would require to implement it in every tap where we want to support it. Which db tap type you're interested in to have this feature?

**Comment by cruzzan** [comment]
@koszti alright, thanks for that feedback! We are trying to use the mysql-tap. Is there any chance that this feature will begin to be introduced any time soon?

**Comment by Samira-El** [comment]
Hi @cruzzan , I believe tap-mysql supports views now.
