### ISSUE TITLE
ERROR: Command failed. Return code: 1

### ISSUE THREAD

**Issue by shamshiranees** [transferwise/pipelinewise#246]
Getting error on running the command.
pipelinewise run_tap --tap postgres_sample --target mypostgres.

Error
2019-10-23 11:36:39 INFO: Running postgres_sample tap in mypostgres target
2019-10-23 11:36:39 INFO: No table available that needs to be sync by fastsync
2019-10-23 11:36:39 INFO: Table(s) selected to sync by singer: ['public-student']
2019-10-23 11:36:39 INFO: Writing output into /root/.pipelinewise/mypostgres/postgres_sample/log/mypostgres-postgres_sample-20191023_113639.singer.log
2019-10-23 11:36:40 ERROR: Command failed. Return code: 1
2019-10-23 11:36:40 INFO: 
-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:01.108270
-------------------------------------------------------

pipelinewise status:-
Tap ID           Tap Type      Target ID    Target Type      Enabled    Status    Last Sync            Last Sync Result
---------------  ------------  -----------  ---------------  ---------  --------  -------------------  ------------------
postgres_sample  tap-postgres  mypostgres   target-postgres  True       ready     2019-10-23T11:36:39  failed
1 pipeline(s)

**Comment by guy-adams** [comment]
@shamshiranees  - what is the content of "/root/.pipelinewise/mypostgres/postgres_sample/log/mypostgres-postgres_sample-20191023_113639.singer.log.*"

**Comment by shamshiranees** [comment]
INFO Selected streams: ['public-student']
INFO found currently_syncing: public-student
INFO Beginning sync of stream(public-student) with sync method(incremental)
INFO Stream public-student is using incremental replication with replication key last_update
INFO TARGET_POSTGRES - Running query: SELECT LOWER(schema_name) schema_name FROM information_schema.schemata WHERE LOWER(schema_name) = %s
CRITICAL 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/app/.virtualenvs/tap-postgres/bin/tap-postgres", line 11, in <module>
    load_entry_point('pipelinewise-tap-postgres==1.1.9', 'console_scripts', 'tap-postgres')()
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 794, in main
    raise exc
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 791, in main
    main_impl()
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 785, in main_impl
    do_sync(conn_config, args.catalog.to_dict() if args.catalog else args.properties, args.config.get('default_replication_method'), state, st$
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 691, in do_sync
    state = sync_traditional_stream(conn_config, stream, state, sync_method_lookup[stream['tap_stream_id']], end_lsn)
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 563, in sync_traditional_stream
    state = do_sync_incremental(conn_config, stream, state, desired_columns, md_map)
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/__init__.py", line 473, in do_sync_incremental
    state = incremental.sync_table(conn_config, stream, state, desired_columns, md_map)
  File "/app/.virtualenvs/tap-postgres/lib/python3.7/site-packages/tap_postgres/sync_strategies/incremental.py", line 53, in sync_table
    replication_key_sql_datatype = md_map.get(('properties', replication_key)).get('sql-datatype')
AttributeError: 'NoneType' object has no attribute 'get'
INFO TARGET_POSTGRES - Running query: SELECT table_name FROM information_schema.tables WHERE table_schema = %s

INFO Table 'student' does not exist. Creating... CREATE TABLE IF NOT EXISTS public.student ("_sdc_batched_at" timestamp without time zone, "_s$
INFO TARGET_POSTGRES - Running query: CREATE TABLE IF NOT EXISTS public.student ("_sdc_batched_at" timestamp without time zone, "_sdc_deleted_$
INFO Granting SELECT ON ALL TABLES privilegue on 'public' schema to 'grp_stats'... GRANT SELECT ON ALL TABLES IN SCHEMA public TO GROUP grp_st$
INFO TARGET_POSTGRES - Running query: GRANT SELECT ON ALL TABLES IN SCHEMA public TO GROUP grp_stats
Traceback (most recent call last):
  File "/app/.virtualenvs/target-postgres/bin/target-postgres", line 11, in <module>
    load_entry_point('pipelinewise-target-postgres==1.0.4', 'console_scripts', 'target-postgres')()
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/__init__.py", line 234, in main
    state = persist_lines(config, input)
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/__init__.py", line 171, in persist_lines
    stream_to_sync[stream].sync_table()
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/db_sync.py", line 547, in sync_table
    self.grant_privilege(self.schema_name, self.grantees, self.grant_select_on_all_tables_in_schema)
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/db_sync.py", line 433, in grant_privilege
    grant_method(schema, grantee)
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/db_sync.py", line 427, in grant_select_on_all_tables_in_$
    self.query(query)
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/target_postgres/db_sync.py", line 279, in query
    params
  File "/app/.virtualenvs/target-postgres/lib/python3.7/site-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.UndefinedObject: role "grp_stats" does not exist


-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:01.296107
-------------------------------------------------------

**Comment by koszti** [comment]
```
Running query: GRANT SELECT ON ALL TABLES IN SCHEMA public TO GROUP grp_stats
psycopg2.errors.UndefinedObject: role "grp_stats" does not exist
```
This means in your `postgres_sample` YAML there is a line that tries to grant permissions on the replicated tables to the `grp_stats` group. You need to create this group first in your postgres DB or simply comment `target_schema_select_permissions:` from the YAML and re-import the project.

**Comment by shamshiranees** [comment]
@koszti thank you above issue solved. please let me know How do I migrate a table without primary key. it doesn't work for me.
