### ISSUE TITLE
Error importing with encrypted password

### ISSUE THREAD

**Issue by robthompsonweb** [transferwise/pipelinewise#392]
Following the docs to encrypt a password, I can encrypt fine but when I try and import it doesnt seem to be able to find the secret file.

`$ echo "password" > vault-password.txt`

`$ pipelinewise encrypt_string --secret vault-password.txt --string "rre^GGD$difvd43Hds"
!vault |
          $ANSIBLE_VAULT;1.1;AES256.....`

`$ pipelinewise  import --dir pipelinewise_live --secret vault-password.txt 
time=2020-04-24 14:02:52 logger_name=pipelinewise.cli.config log_level=INFO message=Searching YAML config files in /app/wrk
time=2020-04-24 14:02:52 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TARGET: target_postgres.yml
Traceback (most recent call last):
  File "/app/.virtualenvs/pipelinewise/bin/pipelinewise", line 11, in <module>
    load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')()
  File "/app/pipelinewise/cli/__init__.py", line 160, in main
    getattr(ppw_instance, args.command)()
  File "/app/pipelinewise/cli/pipelinewise.py", line 1161, in import_project
    config = Config.from_yamls(self.config_dir, self.args.dir, self.args.secret)
  File "/app/pipelinewise/cli/config.py", line 50, in from_yamls
    target_data = utils.load_yaml(os.path.join(yaml_dir, yaml_file), vault_secret)
  File "/app/pipelinewise/cli/utils.py", line 183, in load_yaml
    secret_file = get_file_vault_secret(filename=vault_secret, loader=DataLoader())
  File "/app/.virtualenvs/pipelinewise/lib/python3.7/site-packages/ansible/parsing/vault/__init__.py", line 379, in get_file_vault_secret
    raise AnsibleError("The vault password file %s was not found" % this_path)
ansible.errors.AnsibleError: The vault password file /app/wrk/vault-password.txt was not found`

**Comment by koszti** [comment]
`The vault password file /app/wrk/vault-password.txt` are  you sure it's the right location? Did you try with absolute path?

**Comment by lucaswiley** [comment]
Was there a resolution on this? I have tried with absolute path and am also experiencing issues. 
```
pipelinewise import --dir pipelines --secret ~/vault-password.txt
```

```
Traceback (most recent call last):
  File "/app/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/app/pipelinewise/cli/__init__.py", line 160, in main
    getattr(ppw_instance, args.command)()
  File "/app/pipelinewise/cli/pipelinewise.py", line 1133, in import_project
    config = Config.from_yamls(self.config_dir, self.args.dir, self.args.secret)
  File "/app/pipelinewise/cli/config.py", line 50, in from_yamls
    target_data = utils.load_yaml(os.path.join(yaml_dir, yaml_file), vault_secret)
  File "/app/pipelinewise/cli/utils.py", line 184, in load_yaml
    secret_file = get_file_vault_secret(filename=vault_secret, loader=DataLoader())
  File "/app/.virtualenvs/pipelinewise/lib/python3.7/site-packages/ansible/parsing/vault/__init__.py", line 379, in get_file_vault_secret
    raise AnsibleError("The vault password file %s was not found" % this_path)
ansible.errors.AnsibleError: The vault password file /Users/lucaswiley/vault-password.txt was not found
```

**Comment by colinbarber** [comment]
hi guys, I dug into this issue and it looks like it's caused because the --dir option actually also determines the mounting directory where the vault-password.txt should be located. 

for example: @robthompsonweb 
this command will work, as long as your vault-password.txt is located in the pipelinewise_live directory. hope it helps

`pipelinewise import --dir pipelinewise_live --secret vault-password.txt`

**Comment by lucaswiley** [comment]
Thanks for clarifying, such a simple fix!

**Comment by Samira-El** [comment]
This seems to be resolved. Closing!
