### ISSUE TITLE
MySQL version 8 incompatibility

### ISSUE THREAD

**Issue by ayhanaltunkaynak** [transferwise/pipelinewise#418]
While importing the tap configuration for MySQL 8.0.16 DB endpoint it's failing by the following error. We tried to update pymysql version but it didn't help. Please give your suggestions.

```Traceback (most recent call last):
  File "/app/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 712, in main
    raise exc
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 709, in main
    main_impl()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 692, in main_impl
    log_server_params(mysql_conn)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/__init__.py", line 658, in log_server_params
    with connect_with_backoff(mysql_conn) as open_conn:
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/tap_mysql/connection.py", line 25, in connect_with_backoff
    connection.connect()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 931, in connect
    self._get_server_information()
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/connections.py", line 1269, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/app/.virtualenvs/tap-mysql/lib/python3.7/site-packages/pymysql/charset.py", line 38, in by_id
    return self._by_id[id]
KeyError: 255

**Comment by aairey** [comment]
@koszti could we update the pymysql dependency to support MySQL 8?

**Comment by koszti** [comment]
did you try if upgrading pymsql solves this problem? @ayhanaltunkaynak says he tried and didn't help

**Comment by ayhanaltunkaynak** [comment]
I think we can use the `str_to_date()` function like `SELECT NULLIF(NOW(), str_to_date("0000-00-00 00:00:00", "%Y-%m-%d %H:%i:%s")); `

In this way, the code can work with all versions of MySQL.

**Comment by koszti** [comment]
upgrading to `pymysql-0.9.3` causing another problem that we need to resolve first. Invalid dates (ie. `2017-02-31 00:00:00`) handled differently starting from `0.8.1` but the current implementation of mysql FastSync requires the old behaviour of the driver.

Further details about the change at the expected behaviour at https://github.com/transferwise/pipelinewise-tap-mysql/pull/25

How the bad dates are currently handled implemented by PPW is at https://github.com/transferwise/pipelinewise/pull/444 <- we need to find a way that's doing the same date conversions by `pymysql-0.9.3`

**Comment by aairey** [comment]
Hi @koszti ,

It seems https://github.com/transferwise/pipelinewise/pull/444 was merged for PPW fastsync.

Can we re-consider upgrading pymysql? As it is blocking MySQL 8 support since the revert of pymysql in https://github.com/transferwise/pipelinewise-tap-mysql/pull/25.

**Comment by aairey** [comment]
@koszti transferwise/pipelinewise#862 was submitted.
Can you review?

**Comment by aairey** [comment]
The PR is approved, who can merge the PR?
@koszti @louis-pie ?

**Comment by nauxliu** [comment]
Any updates?

**Comment by aairey** [comment]
Thanks for submitting the PR @nauxliu .
Nice to hear it has been tested for 2 months straight in your environment as well.

@koszti could we get this PR merged so we can finally close this 3 year old bug?
