### ISSUE TITLE
Shopify Tap issues

### ISSUE THREAD

**Issue by kisuka** [transferwise/pipelinewise#559]
**Describe the bug**
tap-shopify seems to be broken maybe. I have everything setup correctly on Ubuntu 18. I run the tap and get the following error:

```
time=2020-10-22 05:23:20 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2020-10-22 05:23:20 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running shopify tap in postgres_dwh target
Traceback (most recent call last):
  File "/home/ubuntu/pipelinewise/pipelinewise/cli/pipelinewise.py", line 154, in create_filtered_tap_properties
    for stream_idx, stream in enumerate(properties.get('streams', tap_properties)):
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/pipelinewise/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/home/ubuntu/pipelinewise/pipelinewise/cli/__init__.py", line 230, in main
    getattr(ppw_instance, args.command)()
  File "/home/ubuntu/pipelinewise/pipelinewise/cli/pipelinewise.py", line 983, in run_tap
    create_fallback=True)
  File "/home/ubuntu/pipelinewise/pipelinewise/cli/pipelinewise.py", line 270, in create_filtered_tap_properties
    raise Exception(f'Cannot create JSON file - {exc}')
Exception: Cannot create JSON file - 'NoneType' object has no attribute 'get'
```

Debug:

```

time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.utils file=/home/ubuntu/pipelinewise/pipelinewise/cli/utils.py:115 log_level=DEBUG message=Saving JSON /root/.pipelinewise/tmp/target_config_0br9q5ut.json
time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.pipelinewise file=/home/ubuntu/pipelinewise/pipelinewise/cli/pipelinewise.py:144 log_level=DEBUG message=Filtering properties JSON by conditions: {'selected': True, 'target_type': ['target-snowflake', 'target-redshift', 'target-postgres'], 'tap_type': ['tap-mysql', 'tap-postgres', 'tap-s3-csv', 'tap-mongodb'], 'initial_sync_required': True}
time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.utils file=/home/ubuntu/pipelinewise/pipelinewise/cli/utils.py:88 log_level=DEBUG message=Parsing file at /root/.pipelinewise/postgres_dwh/shopify/properties.json
time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.utils file=/home/ubuntu/pipelinewise/pipelinewise/cli/utils.py:93 log_level=DEBUG message=No file at /root/.pipelinewise/postgres_dwh/shopify/properties.json
time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.utils file=/home/ubuntu/pipelinewise/pipelinewise/cli/utils.py:88 log_level=DEBUG message=Parsing file at /root/.pipelinewise/postgres_dwh/shopify/state.json
time=2020-10-22 05:27:18 logger_name=pipelinewise.cli.utils file=/home/ubuntu/pipelinewise/pipelinewise/cli/utils.py:93 log_level=DEBUG message=No file at /root/.pipelinewise/postgres_dwh/shopify/state.json

```

Seems the state.json and properties.json are not being populated when using tap-shopify.

**Your environment**
 - Version of PipelineWise: 0df6d15b4d1aa320543246f8d50cc979295c2a1f
 - Source type and setup: shopify
 - Target type and setup: postgres

**Comment by kisuka** [comment]
Nevermind, seems to work now. Had to do discover_tap first then do run_tap.
