### ISSUE TITLE
tap-mysql, target-postgres error failed TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'

### ISSUE THREAD

**Issue by lephuhai** [transferwise/pipelinewise#647]
**To Reproduce**
1. Pipeline status is Ready
2. Run the command to for tap-mysql and target-postgres `pipelinewise run_tap --tap mysql_web_warehouse --target postgres_dwh`
3. All data sync successfully but status TAP RUN SUMMARY is FAILED
4. See error:  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7351351/110625663-470bc100-81d2-11eb-8f8d-83ef626ba369.png)

**Your environment**
 - Version of PipelineWise 0.31.1
 - target-mysql
 - tap-mysql

**Full exception logs**
```
Traceback (most recent call last):
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/bin/target-postgres", line 5, in <module>
    from target_postgres import main
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/__init__.py", line 13, in <module>
    from joblib import Parallel, delayed, parallel_backend
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/target-postgres/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
time=2021-03-10 18:45:52 logger_name=tap_mysql log_level=INFO message=Server Parameters: version: 5.7.33-log, wait_timeout: 28800, innodb_lock_wait_timeout: 3600, max_allowed_packet: 4194304, interactive_timeout: 28800
time=2021-03-10 18:45:52 logger_name=tap_mysql log_level=INFO message=Server SSL Parameters(blank means SSL is not active): [ssl_version: ], [ssl_cipher: ]
time=2021-03-10 18:45:54 logger_name=tap_mysql log_level=CRITICAL message=[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/bin/tap-mysql", line 8, in <module>
    sys.exit(main())
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 404, in main
    raise exc
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 401, in main
    main_impl()
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 394, in main_impl
    do_sync(mysql_conn, args.config, catalog, state)
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 345, in do_sync
    sync_non_binlog_streams(mysql_conn, non_binlog_catalog, config, state)
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/tap_mysql/__init__.py", line 329, in sync_non_binlog_streams
    singer.write_message(singer.StateMessage(value=copy.deepcopy(state)))
  File "/home/vietworm/Documents/pipelinewise/.virtualenvs/tap-mysql/lib/python3.8/site-packages/singer/messages.py", line 281, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:02:40.047771
-------------------------------------------------------
```

**Comment by lephuhai** [comment]
Ref #591

**Comment by Samira-El** [comment]
Hey,
This issue is in `cloudpickle` incompatibility with Python 3.8. cloudpickle is used by joblib which in turn is used by https://github.com/transferwise/pipelinewise-target-postgres

Can you check what version of `joblib` is installed in the `target-postgres` virtual environment?

**Comment by lephuhai** [comment]
Hi @Samira-El,

I did check about that, `joblib` version installed in the `target-postgres` is **0.13.2**

Are you have any solution to fix this issue?

**Comment by lephuhai** [comment]
I downgrade the Python version to **3.7.7** and it's working fine!

It's a solution right away.

**Comment by lephuhai** [comment]
Thanks, @Samira-El  give me more information about the exception above.
