### ISSUE TITLE
When running on a Windows machine, sample pipelines do not run

### ISSUE THREAD

**Issue by rhaycock** [transferwise/pipelinewise#770]
### Subject of the issue
When I remove the `sample` suffix from any tap and any target, and fill in credentials, the import seems to fail, and the pipeline will not run. When I run `pipelinewise import --dir pipelinewise_samples`, I see:

```
time=2021-08-13 05:38:43 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=Searching YAML config files in pipelinewise_samples
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TARGET: target_snowflake.yml
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=LOADING TAP: tap_snowflake.yml
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING CONFIG
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING MAIN CONFIG JSON to /root/.pipelinewise/config.json
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING TARGET JSONS to /root/.pipelinewise/snowflake/config.json
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.config log_level=INFO message=SAVING TAP JSONS to /root/.pipelinewise/snowflake/snowflake_sample
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=ACTIVATING TAP STREAM SELECTIONS...
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 5 concurrent workers.
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Discovering snowflake_sample (tap-snowflake) tap in snowflake (target-snowflake) target...
time=2021-08-13 05:38:43 logger_name=pipelinewise.cli.commands log_level=ERROR message=/bin/bash: /opt/pipelinewise/dev-project/.virtualenvs/tap-snowflake/bin/tap-snowflake: No such file or directory

[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:    0.0s finished
time=2021-08-13 05:38:44 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=
            -------------------------------------------------------
            IMPORTING YAML CONFIGS FINISHED
            -------------------------------------------------------
                Total targets to import        : 1
                Total taps to import           : 1
                Taps imported successfully     : 0
                Taps failed to import          : ['snowflake - snowflake_sample: /bin/bash: /opt/pipelinewise/dev-project/.virtualenvs/tap-snowflake/bin/tap-snowflake: No such file or directory\n']
                Runtime                        : 0:00:00.104011
            -------------------------------------------------------
```

When I run `pipelinewise status`, I see

`time=2021-08-13 05:38:57 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
Tap ID            Tap Type       Target ID    Target Type       Enabled    Status    Last Sync    Last Sync Result
----------------  -------------  -----------  ----------------  ---------  --------  -----------  ------------------
snowflake_sample  tap-snowflake  snowflake    target-snowflake  True       ready                  unknown
1 pipeline(s)`

And finally, when I run `pipelinewise run_tap --tap snowflake_sample --target snowflake`, I see

```
time=2021-08-13 05:41:45 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running snowflake_sample tap in snowflake target
Traceback (most recent call last):
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 155, in create_filtered_tap_properties
    for stream_idx, stream in enumerate(properties.get('streams', tap_properties)):
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pipelinewise/dev-project/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/opt/pipelinewise/pipelinewise/cli/__init__.py", line 230, in main
    getattr(ppw_instance, args.command)()
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 985, in run_tap
    create_fallback=True)
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 271, in create_filtered_tap_properties
    raise Exception(f'Cannot create JSON file - {exc}') from exc
Exception: Cannot create JSON file - 'NoneType' object has no attribute 'get'
```

### Your environment
* Version of PipelineWise: 0.35.0
* Source type and setup Jira (but have tried Snowflake and S3 as well)
* Target type and setup S3 (but have tried Snowflake as well)
* Running on Windows

### Steps to reproduce
Tell us how to reproduce this issue.

I could not run the instructions on the documentation as I am running Windows. See above, but prior to the above commands, I instead do the following:

`git clone https://github.com/transferwise/pipelinewise.git`
then (this is slightly different than the docs):
CHANGE THE FOLLOWING LINE ENDINGS FROM CRLF TO LF:
ci_check_no_file_changes.sh
init_rs.sh
create_user.sh
entrypoint.sh (two of these files)
install.sh
pipelinewise-docker
then I run:
`cd ./pipelinewise/dev-project`
then I run `docker-compose up -d`

the containers are built

then `cd ..` (up one folder, now we are in /pipelinewise

then `docker build -t pipelinewise:latest .`

And after waiting about 10-15 min, I bash into the container:

`docker exec -it pipelinewise_dev bash`

and then I run the sample commands in here: https://transferwise.github.io/pipelinewise/installation_guide/creating_pipelines.html

### Expected behaviour
The pipeline should run.

### Actual behaviour
Pipelines do not run

### Further notes
Tell us why you think this might be happening, or stuff you tried that didn't work

It seems, based on the error message above, `properties` is None and so `tap_properties` is empty. This may be an issue with Windows, but I have changed all shell script files line endings to accommodate.

**Comment by Samira-El** [comment]
Hey, 
From the error `/opt/pipelinewise/dev-project/.virtualenvs/tap-snowflake/bin/tap-snowflake: No such file or directory` it looks like you haven't installed the `tap-snowflake` connector, try running `./install.sh --connectors=tap-snowflake`.

**Comment by rhaycock** [comment]
> Hey,
> From the error `/opt/pipelinewise/dev-project/.virtualenvs/tap-snowflake/bin/tap-snowflake: No such file or directory` it looks like you haven't installed the `tap-snowflake` connector, try running `./install.sh --connectors=tap-snowflake`.

When I bash into the container and then run that command in the `pipelinewise` folder (as opposed to `dev-projects`), things start to install until it reaches these steps:

```
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from requests->messytables==0.15.*->pipelinewise==0.35.0) (2.0.4)
Requirement already satisfied: oauthlib>=3.0.0 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from requests-oauthlib>=0.5.0->msrest>=0.6.18->azure-storage-blob<13.0.0,>=12.0.0->snowflake-connector-python[pandas]==2.4.6->pipelinewise==0.35.0) (3.1.1)
Requirement already satisfied: aiohttp<4.0.0,>3.5.2 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from slackclient<2.10,>=2.7->pipelinewise==0.35.0) (3.7.4.post0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from aiohttp<4.0.0,>3.5.2->slackclient<2.10,>=2.7->pipelinewise==0.35.0) (3.0.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from aiohttp<4.0.0,>3.5.2->slackclient<2.10,>=2.7->pipelinewise==0.35.0) (5.1.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from aiohttp<4.0.0,>3.5.2->slackclient<2.10,>=2.7->pipelinewise==0.35.0) (1.6.3)
Requirement already satisfied: backports.entry-points-selectable>=1.0.4 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit==2.13.0->pipelinewise==0.35.0) (1.1.0)
Requirement already satisfied: platformdirs<3,>=2 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit==2.13.0->pipelinewise==0.35.0) (2.2.0)
Requirement already satisfied: filelock<4,>=3.0.0 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit==2.13.0->pipelinewise==0.35.0) (3.0.12)
Requirement already satisfied: distlib<1,>=0.3.1 in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from virtualenv>=20.0.8->pre-commit==2.13.0->pipelinewise==0.35.0) (0.3.2)
Requirement already satisfied: webencodings in ./.virtualenvs/pipelinewise/lib/python3.7/site-packages (from html5lib->messytables==0.15.*->pipelinewise==0.35.0) (0.5.1)
Installing collected packages: argparse, ansible, unify, python-dotenv, pytest-dependency, pytest-cov, pylint, pipelinewise, mock
```

and it just hangs here indefinitely.

You're right in that the logs right after building the image show this:

```Installed components:

--------------------------------------------------------------------------


Component            Version

-------------------- -------

pipelinewise         0.35.0

tap-mongodb          1.2.0

tap-mysql            1.4.3

tap-postgres         1.8.0

tap-s3-csv           1.2.2

target-bigquery      1.1.1

target-postgres      2.1.0

target-snowflake     1.13.1

transform-field      2.1.0
```

but why is tap-snowflake not installing fully?

**Comment by rhaycock** [comment]
So now I see:

```
Component            Version
-------------------- -------
pipelinewise         0.35.0
tap-jira
tap-snowflake        2.0.3
target-snowflake     1.13.1
```

and I check pipeline status:

```
time=2021-08-13 23:00:52 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
Tap ID            Tap Type       Target ID    Target Type       Enabled    Status    Last Sync    Last Sync Result
----------------  -------------  -----------  ----------------  ---------  --------  -----------  ------------------
snowflake_sample  tap-snowflake  snowflake    target-snowflake  True       ready                  unknown
1 pipeline(s)
```
then I run `pipelinewise run_tap --tap snowflake_sample --target snowflake` and I get this error:

```
time=2021-08-13 23:08:08 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2021-08-13 23:08:08 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running snowflake_sample tap in snowflake target
Traceback (most recent call last):
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 155, in create_filtered_tap_properties
    for stream_idx, stream in enumerate(properties.get('streams', tap_properties)):
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pipelinewise/dev-project/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/opt/pipelinewise/pipelinewise/cli/__init__.py", line 230, in main
    getattr(ppw_instance, args.command)()
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 985, in run_tap
    create_fallback=True)
  File "/opt/pipelinewise/pipelinewise/cli/pipelinewise.py", line 271, in create_filtered_tap_properties
    raise Exception(f'Cannot create JSON file - {exc}') from exc
Exception: Cannot create JSON file - 'NoneType' object has no attribute 'get'
```

**Comment by rhaycock** [comment]
As a final but very important note, I will mention that I _strongly_ believe a cause for this error might be the failure of importing one of the sample pipelines. When I start the process from scratch, I consistently get errors (various) when attempting to activate/import pipelines using `pipelinewise import --dir pipelinewise_samples`. The errors depend on what information (password, username, etc.) I put into the .yml files (and yes I am removing the .sample suffix).

**Comment by rhaycock** [comment]
I managed to resolve the issues and I was wondering how can I contribute a new set of instructions for Windows users using Linux containers in Docker?

**Comment by Samira-El** [comment]
Hi @rhaycock, I have answered in the discussions section https://github.com/transferwise/pipelinewise/discussions/780.

Feel free to close this issue.

**Comment by Samira-El** [comment]
Closing as no activity!
