### ISSUE TITLE
Non-core singer-connectors do not run

### ISSUE THREAD

**Issue by alastairstuart** [transferwise/pipelinewise#800]
**Describe the bug**
Any singer-connector not specified in `pipelinewise/cli/constants.py` will not run

**To Reproduce**
1. Configure and import tap_shopify or any other tap not listed in contants.py
2. Run the tap

**Expected behavior**
Tap Runs

**Screenshots**
```
(pipelinewise) ~/dev/mc-pipelinewise-config(master ✗) cd /Users/al/dev/mc-pipelinewise-config &&         
pipelinewise run_tap --tap shopify --target postgres_warehouse
time=2021-09-20 17:23:06 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2021-09-20 17:23:06 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running shopify tap in postgres_warehouse target
ValueError: 'tap-shopify' is not a valid ConnectorType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/al/dev/pipelinewise/.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/Users/al/dev/pipelinewise/pipelinewise/cli/__init__.py", line 253, in main
    getattr(ppw_instance, args.command)()
  File "/Users/al/dev/pipelinewise/pipelinewise/cli/pipelinewise.py", line 1189, in run_tap
    ConnectorType(tap_type),
  File "/usr/local/Cellar/python@3.7/3.7.12/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python@3.7/3.7.12/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 569, in __new__
    raise exc
  File "/usr/local/Cellar/python@3.7/3.7.12/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 553, in __new__
    result = cls._missing_(value)
  File "/usr/local/Cellar/python@3.7/3.7.12/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 582, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 'tap-shopify' is not a valid ConnectorType

```

**Your environment**
 - 0.35.2
 - tap_shopify
 - target_postgres

**Additional context**

**Comment by Samira-El** [comment]
Hey, thanks for reporting this, looking into it.

**Comment by Samira-El** [comment]
Should be fixed now by https://github.com/transferwise/analytics-platform-config/pull/4602
Please try again.

**Comment by Samira-El** [comment]
Closing due to inactivity!
